### ISSUE TITLE
retina

### ISSUE THREAD

**Issue by nyanhan** [twolfson/spritesmith#19]
I like this tool, it's great. And can give support of 2x zoom sprite support ? 
Or is there some solution ? thx.

**Comment by dhenriet** [comment]
Hi ! Thanks for this great tool I can say goodbye to Compass :)
I had same problem that @squallstar with sort and algorithm for `/icons/*.png` and `/icons-2x/*.png` (103 icons). 
This is working nice with a little more configuration and CSS : 

```js
sprite:{
            icons: {
                cssSpritesheetName: 'icons',
                src: dir.styles.img +'/icons/*.png',
                dest: dir.styles.img +'/icons.png',
                imgPath: dir.assets.img +'/icons',
                destCss: dir.styles.src +'/base/_icons.scss',
                cssTemplate: dir.styles.src +'/base/_icons.scss.mustache',
                padding: 2
            },
            icons2x: {
                cssSpritesheetName: 'icons',
                src: dir.styles.img +'/icons-2x/*.png',
                dest: dir.styles.img +'/icons-2x.png',
                imgPath: dir.assets.img +'/icons-2x',
                destCss: dir.styles.src +'/base/_icons2x.scss',
                cssTemplate: dir.styles.src +'/base/_icons2x.scss.mustache',
                padding: 2
            }
          
        },
```

```scss
@import 'base/icons';
@import 'base/icons2x';
```

```js
//== _icons.scss.mustache
.{{spritesheet_name}}- {
    display: inline-block;
    vertical-align: middle;
    background-image: url('{{{spritesheet.escaped_image}}}.png');
    background-repeat: no-repeat;

    @media only screen and (-webkit-min-device-pixel-ratio: 2),
    only screen and (   min--moz-device-pixel-ratio: 2),
    only screen and (     -o-min-device-pixel-ratio: 2/1),
    only screen and (        min-device-pixel-ratio: 2),
    only screen and (                min-resolution: 192dpi),
    only screen and (                min-resolution: 2dppx) {
        background-image: url('{{{spritesheet.escaped_image}}}-2x.png');
    }
}

{{#items}}
    .{{spritesheet_name}}-{{name}} {
        @extend .{{spritesheet_name}}-;
        width: {{px.width}};
        height: {{px.height}};
        background-position: {{px.offset_x}} {{px.offset_y}};
    }
{{/items}}

//== _icons2x.scss.mustache
@media only screen and (-webkit-min-device-pixel-ratio: 2),
only screen and (   min--moz-device-pixel-ratio: 2),
only screen and (     -o-min-device-pixel-ratio: 2/1),
only screen and (        min-device-pixel-ratio: 2),
only screen and (                min-resolution: 192dpi),
only screen and (                min-resolution: 2dppx) {
    [class*="icons"] {
        background-size: ({{spritesheet.px.width}}/2) ({{spritesheet.px.height}}/2);
    }
{{#items}}
    .{{spritesheet_name}}-{{name}} {
        background-position: ({{px.offset_x}}/2) ({{px.offset_y}}/2);
    }
{{/items}}
}
```

**Comment by twolfson** [comment]
We have added retina support in `grunt-spritesmith@4.5.0`. `gulp.spritesmith` is planned over this week. More `grunt-spritesmith` specific information can be found here:

https://github.com/Ensighten/grunt-spritesmith#retina-parameters

https://github.com/Ensighten/grunt-spritesmith#retina-spritesheet

**Comment by hudochenkov** [comment]
Thank you, this is long awaiting features :)

**Comment by bezoerb** [comment]
awesome :)
Thanks

**Comment by twolfson** [comment]
I was able to complete `gulp.spritesmith` before it got too late =) `gulp.spritesmith@3.5.0` now supports retina spritesheets as well.

https://github.com/twolfson/gulp.spritesmith#retina-parameters

https://github.com/twolfson/gulp.spritesmith#retina-spritesheet

**Comment by dhenriet** [comment]
great ! thanks

**Comment by SunLn** [comment]
Sorry to trouble u. I want to use retina-spritesheet feature.
I am using gulp.spritesmith 、coffeescript 、sass ， But it doesnot work well.
My gulpfile.coffee code is :

```
ASSETS_PATH = 'static/'
cssSpriteOption2 =
  imgName: 'sprite.png'
  cssName: 'sprite.scss'
  retinaImgName: 'sprite-2x.png'
  retinaImgPath : '../img/sprite-2x.png'
  retinaSrcFilter: ASSETS_PATH + 'img/css-sprite/*-2x.png'
  cssFormat: 'css'
  padding: 1

gulp.task 'sprites2', ->
  spriteData = gulp.src [ASSETS_PATH + 'img/css-sprite/*.png']
    .pipe spritesmith cssSpriteOption2
  spriteData.img.pipe(gulp.dest DIST_PATH + 'img/')
  spriteData.css.pipe(gulp.dest ASSETS_PATH + 'css/sass/')

```

When I run 'gulp sprites2' ，It produces two images ,named 'sprite-2x.png' and 'sprite.png' .

But only one sass file like below 
```
.icon-contact {
  background-image: url(sprite.png);
  background-position: 0px 0px;
  width: 74px;
  height: 67px;
}
```
Should it  like this ?

```
.icon-contact {
  background-image: url(sprite.png);
  background-position: 0px 0px;
  width: 74px;
  height: 67px;
}

@media only screen and (-webkit-min-device-pixel-ratio: 1.5), screen and (min-device-pixel-ratio: 1.5) {
    .icon-contact {
      background-image: url(sprite-2x.png);
      background-position: 0px 0px;
      width: 74px;
      height: 67px;
      background-size :  A1px  A2px;
    }
  }
```

My English is not so good . Hope to get your help.
Thanks a lot.

**Comment by twolfson** [comment]
You are specifying the `cssFormat` which is causing the default retina template to be overridden to its non-retina equivalent. To remedy this, either update `cssFormat` to `css_retina` or remove it and leverage the SCSS `retina-sprites` mixin instead.

https://github.com/twolfson/gulp.spritesmith/tree/3.5.3#retina-parameters

**Comment by SunLn** [comment]
Thanks.I get it .

**Comment by KuDim89** [comment]
Hi, I have problem with spritesmith( I see in browser -    
 background-image: url(../destination/spritesheet.png);
    background-position: extract('user', 3) extract('user', 4);
    width: extract('user', 5);
    height: extract('user', 6);
How I can  change this to see the sprite?

**Comment by twolfson** [comment]
@KuDim89 Please open a separate issue explaining the error message you are seeing. This issue has been inactive for 3 years
