### ISSUE TITLE
svg format support?

### ISSUE THREAD

**Issue by twobit** [twolfson/spritesmith#36]
The README only mentions support for png or jpeg. Is there any support for svg sprite sheets?

**Comment by patricknelson** [comment]
I know this is old, but chiming in on support for generating SVG sprites.

So, fonts actually _are_ great for shipping many vectorized graphics as a single file or set of files; the primary use case for this is to facilitate dynamic color. However, that only works if the vector graphics you're converting into a sprite is monotone. I still have a need to generate SVG sprite sheets from multi-color vector graphics. My issue is that other libraries (like `grunt-svg-sprite`) rely still on the ancient/dead `phantomjs` project, which becomes **_really_** difficult to support as time progresses. A project that still "haunts" me to this day, if you will.
