### ISSUE TITLE
Add cachebusting to generated spritename

### ISSUE THREAD

**Issue by leevigraham** [twolfson/spritesmith#37]
It would be great if a hash of the sprite could be generated and added to the output of spritesmith.

**Comment by yonidor** [comment]
Would you like to have cacheBust as an option of the spritesmith task (which internally will use grunt-cache-breaker)?

**Comment by twolfson** [comment]
It's possible but it doesn't cover the majority of the use cases (e.g. doesn't support SCSS, Stylus).
