### ISSUE TITLE
Produces slightly different output every run

### ISSUE THREAD

**Issue by danny6514** [twolfson/spritesmith#77]
I'm currently using spritesmith with the default engine to compile hundreds of sprite images. However, after each run, the generated image is always slightly different. This difference is resulting in different cache buster being generated, effectively busting the cache everytime.

I've tried pixelsmith and canvassmith, but both result in slightly different image everytime. Is there any way to guarantee that the generated image will only change if the input files change?

**Comment by twolfson** [comment]
What is the format of the image you're generating? (e.g. PNG, JPG, GIF)

**Comment by danny6514** [comment]
JPG

**Comment by twolfson** [comment]
JPG artifacts are inherently random, there's no way to avoid the signature changing =/ To avoid the issue, you can:

- Switch to PNG
- Add a "last modified" comparison check between the source files and the target file (i.e. if target file's timestamp is greater than all of the source files, then don't recompile)
    - If you're using Grunt or gulp, there are plenty of plugins for these

**Comment by danny6514** [comment]
Sorry I don't know what I was thinking yesterday, but the images are actually already PNG.
