### ISSUE TITLE
Output image not giving exact dimension

### ISSUE THREAD

**Issue by indumathyn** [twolfson/spritesmith#80]
While am generating sprite using 2 image files consumes 2 kb each with 640*360 dimension

Why output not generating as 4kb?taking more than 4kb than actual size.
So there any option to compress image size?

**Comment by twolfson** [comment]
Not all image encoders are created equally, we don't specialize in image optimization -- only spritesheet and variable creation

We recommend looking for image optimizers (e.g. `pngcrush`, `imagemin`) and using those on the image result
