### ISSUE TITLE
Add a margin option

### ISSUE THREAD

**Issue by Juankz** [twolfson/spritesmith#81]
White space between the sprites and the image borders helps avoid some scaling artifacts.

**Comment by twolfson** [comment]
This feature is available via the `padding` option in `processImages`:

https://github.com/twolfson/spritesmith/tree/3.4.0#spritesheetprocessimagesimages-options

Here's an example usage:

https://github.com/twolfson/spritesmith/tree/3.4.0#padding

If you're using our `Grunt` or `gulp` variants, then it's `padding` in the `params` object:

https://github.com/twolfson/gulp.spritesmith/tree/6.11.0#spritesmithparams

https://github.com/twolfson/grunt-spritesmith/tree/6.8.0#documentation

**Comment by Juankz** [comment]
Hi, thanks for answering. If I'm not mistaken, padding give this result (yellow = padding): 
![current](https://user-images.githubusercontent.com/18577412/88308395-95fff700-ccd2-11ea-8be4-83e5d640a382.png)

But I'm looking for this (green = margin):
![desired](https://user-images.githubusercontent.com/18577412/88308399-96988d80-ccd2-11ea-86bb-62bf93052f80.png)

**Comment by twolfson** [comment]
I see. Can you explain your use case further? I know padding between images is good for artifacts based on past issues (https://github.com/twolfson/spritesmith/issues/7) but haven't heard about margin having that effect

**Comment by Juankz** [comment]
Yeah, no problem, I've also thought about other ways to solve this issue. Thanks for your time

**Comment by twolfson** [comment]
Cool, yea =/ Thanks for understanding =) If more people write in about it,
then we'll gladly revisit =)

And still glad to help you work through any of those workarounds =)
