### ISSUE TITLE
Nested dependency json-schema suffers from a security vulnerability: GHSA-896r-f27r-55mw

### ISSUE THREAD

**Issue by nima-ap** [twolfson/spritesmith#87]
Hi
The following security vulnerability exists in the package through nested dependencies:

```
spritesmith@3.4.0
  └─┬ pixelsmith@2.5.0
    └─┬ get-pixels@3.3.3
      └─┬ request@2.88.2
        └─┬ http-signature@1.2.0
          └─┬ jsprim@1.4.1
            └── json-schema@0.2.3
```

https://github.com/advisories/GHSA-896r-f27r-55mw

**Comment by twolfson** [comment]
We have a floating dependency there. If the underlying projects install a patch, then we'll receive it. Please open issues and resolve in the dependencies first. I don't have bandwidth at the moment to maintain other packages other than my own.
