### ISSUE TITLE
How to run in browser

### ISSUE THREAD

**Issue by tidys** [twolfson/spritesmith#88]
I tried to run it in this browser and it reported an error
![image](https://user-images.githubusercontent.com/7894208/185937537-c2167255-0a1e-4ccf-b00f-63613252ab70.png)

I found that this error was thrown by [`process-nexttick-args`](https://github.com/calvinmetcalf/process-nextick-args)

The approximate dependency is：

> spritesmith -> concat-stream ->readable-stream->process-nexttick-args

Regarding process.nexttick, [browser-next-tick](https://github.com/wesleytodd/browser-next-tick) is alternative

I tried to fix the process and found that it wasn't very easy

Is there a better way to get this package to run in the browser?

**Comment by twolfson** [comment]
`spritesmith` is not designed to be run in the browser. The normal use case is to generate sprites on the server at build time, then not regenerate them again during runtime. Running in the browser would negate a lot of the benefits
