### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Zenoo** [twolfson/spritesmith#89]
Hi, could you add typescript definitions in your project?

It would be helpful for us typescript users, thanks !

**Comment by twolfson** [comment]
Unfortunately I don't have bandwidth to set this up and am inexperienced with TypeScript. I'd gladly take a PR adding in definitions though =D (assuming that can be done without porting the current code to `.ts`)

**Comment by Zenoo** [comment]
It's done, you can now install the types with `npm i -D @types/spritesmith`, or check out the code on [NPM](https://www.npmjs.com/package/@types/spritesmith)
