### ISSUE TITLE
Webpack warnings and runtime errors implementing the simplest example.

### ISSUE THREAD

**Issue by Baralitill** [twolfson/spritesmith#90]
**So I'm trying to implement this package in my project and I'm literally at the starting line.

I've updated my package.json file with

`"spritesmith": "^3.4.0",`

and run yarn install.

When I run 'yarn webpack' it prints a warning:

```
WARNING in ./node_modules/spritesmith/src/smith.js 23:6-33
Critical dependency: the request of a dependency is an expression
 @ ./src/pages/ChildComponent/childComponent.jsx
 @ ./src/pages/ParentComponent/parentComponent.jsx
 @ ./src/containers/McsRouter/McsRoute.jsx
 @ ./src/entry_points/router.jsx

WARNING in ./node_modules/spritesmith/src/smith.js 35:15-34
Critical dependency: the request of a dependency is an expression
 @ ./src/pages/ChildComponent/childComponent.jsx
 @ ./src/pages/ParentComponent/parentComponent.jsx
 @ ./src/containers/McsRouter/McsRoute.jsx
 @ ./src/entry_points/router.jsx
```

The lines in question are where the package tries to import the engine package,
require.resolve(engineName) and Engine = require(engineName).

I've implemented the simplest example in your docs 

```

var Spritesmith = require('spritesmith');

var spritesmith = new Spritesmith();
```

And here I get a runtime error, where the console reads the printout from your catch statement:

```
try {
      require.resolve(engineName);
    } catch (err) {
      console.error('Attempted to find spritesmith engine "' + engineName + '" but could not.');
      console.error('Please verify you have installed "' + engineName + '" and saved it to your `package.json`');
      console.error('');
      console.error('    npm install ' + engineName + ' --save-dev');
      console.error('');
      throw err;
    }
```

and then below that

```
Uncaught Error: Cannot find module 'pixelsmith'
    at Function.webpackEmptyContext [as resolve] (router.js:222954:10)
    at new Spritesmith (router.js:222994:96)
    at router.js:251524:19
    at commitHookEffectListMount (router.js:196633:26)
    at commitPassiveHookEffects (router.js:196671:11)
    at HTMLUnknownElement.callCallback (router.js:177090:14)
    at Object.invokeGuardedCallbackDev (router.js:177139:16)
    at invokeGuardedCallback (router.js:177194:31)
    at flushPassiveEffectsImpl (router.js:199755:9)
    at unstable_runWithPriority (router.js:218664:12)
```

None of this makes any sense, pixelsmith is installed as a dependency and is accessible in the project. What gives?

Any help would be greatly appreciated.**

**Comment by twolfson** [comment]
I'm not sure what's exactly in your `yarn webpack` but I suspect it's trying to put/run `spritesmith` into a browser context (e.g. seeing `src/pages`, `HTMLUnknownElement` in stack traces)

`spritesmith` is designed to be run on the server as building sprites for use within the browser is antithetical to CSS sprites (i.e. trying to reduce HTTP requests)

We've written up `gulp` and `grunt` implementations that you should be able to use out of the box:

- https://github.com/twolfson/gulp.spritesmith
- https://github.com/twolfson/grunt-spritesmith

There do seem to be `webpack` implementations as well but I have no experience with them:

- https://github.com/mixtur/webpack-spritesmith
- https://github.com/daipeng7/spritesmith-webpack-plugin

Hopefully this helps!

**Comment by Baralitill** [comment]
Thanks for the quick, response. This was very helpful 👍
