### ISSUE TITLE
Semver ~5.0.3 has vulnerability

### ISSUE THREAD

**Issue by gun0317** [twolfson/spritesmith#92]
`semver` of version under 5.7.2 has vulnerability - `Regular Expression Denial of Service (ReDoS)`
https://security.snyk.io/package/npm/semver

Please consider upgrading `semver` to 5.7.2 as this version fixes the issue.

**Comment by twolfson** [comment]
My bandwidth is somewhat limited at the moment. Do you mind creating a PR and testing it?

**Comment by ChrisdeWolf** [comment]
Opened a PR for this - https://github.com/twolfson/spritesmith/pull/95

**Comment by twolfson** [comment]
The fix from @ChrisdeWolf in #95 has been released in `3.5.0`. Changes should auto-propagate to `gulp.spritesmith` and `grunt-spritesmith`. Thanks for all your work y'all!
